name: user
description: "MOMO FOOD"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.8
  flutter_local_notifications: ^19.3.0
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  geolocator: ^14.0.1
  google_maps_flutter: ^2.12.3
  google_maps_flutter_web: ^0.5.12+2
  flutter_typeahead:
  carousel_slider:
  shimmer_animation:
  image_picker:
  universal_html: ^2.0.8
  flutter_inappwebview: ^6.1.4
  expandable_bottom_sheet:
  url_launcher:
  http:
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+2
  flutter_facebook_auth: ^6.0.4
  sign_in_with_apple: ^6.1.1
  pointer_interceptor:
  cached_network_image:
  photo_view:
  dotted_border: ^2.0.0+2
  phone_number: ^1.0.0
  share_plus:
  custom_map_markers:
  card_swiper: ^3.0.1
  modal_bottom_sheet:
  flutter_html: ^3.0.0-alpha.5
  flutter_widget_from_html: ^0.16.0
  intl:
  flutter_slidable:
  just_the_tooltip:
  animated_flip_counter:
  firebase_crashlytics:
  popup_banner:
  animated_text_kit:
  flutter_polyline_points: ^2.1.0
  location:
  flutter_staggered_animations:
  flutter_animate:
  in_app_update:
  upgrader:
  lottie:
  restart_app:
  url_strategy:
  country_code_picker:
  fluttertoast:
  flutter_screenutil:
  loading_animation_widget: ^1.2.1
  flutter_image_compress: ^2.1.0
  dotted_line: ^3.2.3
  gradient_borders: ^1.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons:
  flutter_native_splash:

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/language/
    - assets/font/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
