// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPqRxyfFDj38Nezb-RJDseu6mwXxxPQb0',
    appId: '1:109381590450:web:f84e67010cb0a8128d18ab',
    messagingSenderId: '109381590450',
    projectId: 'momofood-2b75f',
    authDomain: 'momofood-2b75f.firebaseapp.com',
    storageBucket: 'momofood-2b75f.appspot.com',
    measurementId: 'G-W1XBYY3DHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Iv9Et11kMMUIZGUTbBz1LNmTTRdEV4E',
    appId: '1:109381590450:android:5c5886b32601ca2b8d18ab',
    messagingSenderId: '109381590450',
    projectId: 'momofood-2b75f',
    storageBucket: 'momofood-2b75f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtHjhkVybCxZQMSsEKE8yOwU7hhpgoVaE',
    appId: '1:109381590450:ios:a534d102911a7fc08d18ab',
    messagingSenderId: '109381590450',
    projectId: 'momofood-2b75f',
    storageBucket: 'momofood-2b75f.appspot.com',
    iosBundleId: 'com.mmofood.user',
  );
}
